### ISSUE TITLE
Missing requirement - UNAFOLD

### ISSUE THREAD

**Issue by dfajar2** [matdoering/openPrimeR-User#1]
Hi, 
I am having trouble on making openPrimeR to run. 
I have tried different install approaches (Bioconductor: http://www.bioconductor.org/packages/release/bioc/html/openPrimeR.html conda: https://bioconda.github.io/recipes/bioconductor-openprimerui/README.html, docker hub: https://hub.docker.com/r/mdoering88/openprimer/ and github: https://github.com/matdoering/openPrimeR-User ) and always have the same error. 
Even though I have installed all the required third party software it reports an error with oligoarrayaux

The versions of the installed software I'm using are:
R v3.5.1, ViennaRNA v2.4.1, mafft v7.407, phantomjs v2.1.1 MELTING v5.1.1 and oligoarrayaux v.3.8

------------------------------
R error message output

> library(openPrimeR)
There are missing/non-functioning external tools.
To use the full potential of openPrimeR, please make sure
that the required versions of the speciied tools are
installed and that they are functional:
o OligoArrayAux (http://unafold.rna.albany.edu/OligoArrayAux.php)
Warning messages:
1: In check.tool.function() :
  Please define the UNAFOLDDAT variable in your path before using OligoArrayAux.
2: In check.tool.function() :
  Please define the UNAFOLDDAT variable in your path before using OligoArrayAux.
3: In parallel_setup(default.nbr.cores) :
  Please install 'doParallel' to use multiple cores.

**Comment by mattheiter** [comment]
Sorry for the late response. Did you check this solution?

https://github.com/matdoering/openPrimeR/issues/2
