### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by KristinaGagalova** [matdoering/openPrimeR-User#2]
Hi, 
I am installing through git and I have the following error:
```
./install.sh
Using R at:  /usr/bin/R
Loading required package: devtools
Loading required package: usethis
Error: Could not find package root, is your working directory inside a package?
Execution halted
```
Any suggestions?
Thank you in advance

**Comment by JaspervB-tud** [comment]
I'm suffering from the same problem. Has a solution been proposed?

**Comment by mattheiter** [comment]
If you follow the README instructions, it clearly states how to update the git submodules:

```
git submodule update --remote
```

If you run the install without this command, there will be nothing to install. I've added an improved error message to make this clearer.
